[tool.poetry]
name = "codereal"
version = "0.1.0"
description = ""
authors = ["Jesus Almirco"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
